### PR TITLE
Define PRawByteString for older FPC

### PR DESCRIPTION
**Pull request by Bi0T1N**
added in FPC svn 39662

fixes one issue from #274

### CODE REVIEW

**Comment by rlebeau** [comment]
When defining `PRawByteString` in `IdGlobal.pas`, please wrap it in an `{$IFDEF SetCodePage}` block:
```
  {$IFDEF HAS_SetCodePage}
    {$IFNDEF HAS_PRawByteString}
  PRawByteString = ^RawByteString;
    {$ENDIF}
  {$ENDIF}
````
The only time that Indy uses `RawByteString` is when calling `SetCodePage()`, which is not available in Delphi 2007 and earlier.  Your proposed change will not compile in those older versions of Delphi because `RawByteString` did not exist yet.

**Comment by rlebeau** [comment]
`SetCodePage()` and `RawByteString` have been [available in FPC since 3.0](https://wiki.freepascal.org/Unicode_Support_in_Lazarus), but your proposal defines `HAS_PRawByteString` for FPC 3.1.1+ instead. Are you sure that FPC 3.0 did not introduce `PRawByteString` when it introduced `RawByteString`?

**Comment by Bi0T1N** [comment]
1. Added `{$IFDEF HAS_SetCodePage}` around the block. Indy supports to many different compiler versions... :D
2. Yes, I checked it before writing the patch. It was added in svn 39662 (https://github.com/graemeg/freepascal/commit/b3708d24aded4470af5396eceed255b0892c7803) but never made it into 3.0.4 (https://svn.freepascal.org/svn/fpc/tags/release_3_0_4/rtl/inc/systemh.inc) nor in 3.0.4a for MacOS (https://svn.freepascal.org/svn/fpc/tags/release_3_0_4a_macos_10_14/rtl/inc/systemh.inc)

**Comment by rlebeau** [comment]
I merged the pull request, and then added a small tweak of my own on top of it.

**Pull request merged**
